server:
  port: 9002
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/house?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: root
        password: 1234
        initialize: true
  flyway:
    enabled: true #开启flyway功能，默认为true
    table: flyway_schema_history # 用于存储迁移历史记录的表名，默认为flyway_schema_history
    baseline-on-migrate: true # 当迁移数据库存在但没有元数据的表时，自动执行基准迁移，新建flyway_schema_history表
    encoding: UTF-8 # 迁移脚本编码，默认为UTF-8
    clean-on-validation-error: true
    locations: classpath:db/migration # 数据库迁移脚本的位置，默认为classpath:db/migration
    sql-migration-prefix: V # SQL迁移脚本文件名前缀，默认为V
    sql-migration-suffixes: sql # SQL迁移脚本文件名后缀，默认为.sql
    validate-on-migrate: true # 是否在迁移时验证脚本，默认为true
    check-location: false # 检测迁移脚本的路径是否存在，默认为true，如不存在，则抛出异常，如果不想抛出异常可设为flase
    # clean-disabled: true # 用于控制是否禁用 Flyway 的 clean 操作。




## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
   mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
   type-aliases-package: com.house.pojo # 注意：对应实体类的路径
   #mybatis.configuration.map-underscore-to-camel-case=true开启驼峰命名识别
   configuration:
     map-underscore-to-camel-case: true





